### ISSUE TITLE
FileNotFoundError after 51 iterations

### ISSUE THREAD

**Issue by ilyakooo0** [windmaple/stablediffusion-desktop#1]
OS: macOS 12.5.1

After performing 51 iterations I get an error:

```
51it [21:38, 25.46s/it]
Exception in thread Thread-231:
Traceback (most recent call last):
  File "threading.py", line 954, in _bootstrap_inner
  File "threading.py", line 892, in run
  File "SD-desktop.py", line 66, in run_defusion
  File "PIL/Image.py", line 2317, in save
FileNotFoundError: [Errno 2] No such file or directory: 'assets/64094381.png'
```

I tried running it again and still get the exact same behaviour.

**Comment by windmaple** [comment]
Thanks for giving it a try. This is an experiment that I don't intend to maintain (because there are much better projects).

Give [SD-webui](https://github.com/sd-webui/stable-diffusion-webui) a try. It's really good.
